[package]
authors = ["ActivePeter <1020401660@qq.com>"]
edition = "2018"
name = "bevy_voxel"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4.0"
